# Generated by Django 6.0.3 on 2026-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word', models.CharField(max_length=100)),
                ('second_word', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(default=1)),
            ],
        ),
    ]
