# Generated by Django 6.0.3 on 2026-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_wordpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair',
            name='third_word',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordpair',
            name='first_word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wordpair',
            name='second_word',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
